[package]
name = "codeflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = "0.3"
serde_json = "1.0"
